liveface/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls', namespace='face-detect')),
    url(r'^admin/', admin.site.urls),
]

main/urls.py
from django.conf.urls import url

from main.views import ImageFaceDetect, LiveVideoFaceDetect

urlpatterns = [
    url(r'^face-detect/image/$', ImageFaceDetect.as_view(), name='image'),
    url(r'^face-detect/video/$', LiveVideoFaceDetect.as_view(), name='live_video'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse
from django.views.generic import TemplateView

from main.detect import get_face_detect_data


def upload_file(image):
    fs = FileSystemStorage()
    filename = fs.save(image.name, image)
    uploaded_file_url = fs.path(filename)
    return uploaded_file_url


class ImageFaceDetect(TemplateView):
    template_name = 'image.html'

    def post(self, request, *args, **kwargs):
        data = request.POST.get('image')
        try:
            image_data = get_face_detect_data(data)
            if image_data:
                return JsonResponse(status=200, data={'image': image_data, 'message': 'Face detected'})
        except Exception as e:
            pass
        return JsonResponse(status=400, data={'errors': {'error_message': 'No face detected'}})


class LiveVideoFaceDetect(TemplateView):
    template_name = 'video.html'

    def post(self, request, *args, **kwargs):
        return JsonResponse(status=200, data={'message': 'Face detected'})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Face Detect</title>
</head>
<link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
<body>
<div class="container-fluid">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/formsubmit.js' %}"></script>
{% block js %}
{% endblock %}
</html>

templates/image.html
{% extends 'base.html' %}
{% block content %}
    <div class="col s4">
            <div class="collection">
                <a href="{% url 'face-detect:image' %}" class="collection-item active">Simple Face Detection</a>
                <a href="{% url 'face-detect:live_video' %}" class="collection-item">Live Face Detection</a>
            </div>
        </div>
    <div class="col s6">
        <div class="card">
            <div class="card-content center-align">
                <form method="post" id="form-image" enctype="multipart/form-data"
                      action="{% url 'face-detect:image' %}">
                    {% csrf_token %}
                    <h4 class="center"><u>Live Video</u></h4>
                    <video id="video" width="600" height="450" autoplay></video>
                    <canvas id="canvas" width="600" height="450" class="hide"></canvas>
                    <input type="hidden" name="image" id="face-image">
                    <button type="submit" class="btn" id="detect-image" style="margin-bottom: 10px">Detect Face
                    </button>
                    <img src="" id="detect-data" width="600" height="450" class="hide">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(document).ready(function () {
            let video = document.getElementById('video');
            let canvas = document.getElementById('canvas');
            let context = canvas.getContext('2d');
            let face_image = document.getElementById('face-image');
            if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                navigator.mediaDevices.getUserMedia({video: true}).then(function (stream) {
                    video.src = window.URL.createObjectURL(stream);
                    video.play();
                });
            }

            $.DjangoAjaxHandler2({
                submitBtn: '#detect-image',
                form_selector: '#form-image',
                beforeSubmission: function (form, instance) { // after errors are cleared, preprocessing can be done here
                    $(instance.options.submitBtn).val('loading').prop('disabled', true).addClass('disabled');
                    context.drawImage(video, 0, 0, 600, 450);
                    face_image.value = canvas.toDataURL('image/png');
                },
                postSuccess: function (form, response, instance) {
                    form.reset();
                    Materialize.updateTextFields();
                    $('#detect-data').removeClass('hide').attr('src', response['image']);
                    $(instance.options.submitBtn).val('Detect Face').prop('disabled', false).removeClass('disabled');
                },
            });
        })
    </script>
{% endblock %}

templates/video.html
{% extends 'base.html' %}
{% block content %}
    <div class="col s4">
        <div class="collection">
            <a href="{% url 'face-detect:image' %}" class="collection-item">Simple Face Detection</a>
            <a href="{% url 'face-detect:live_video' %}" class="collection-item active">Live Face Detection</a>
        </div>
    </div>
    <div class="col s6">
        <div class="card">
            <div class="card-content center-align">
                <h4 class="center"><u>Live Video</u></h4>
                <video id="video" width="600" height="450" autoplay></video>
                <canvas id="canvas" width="600" height="450" class="hide"></canvas>
                <button type="button" class="btn" id="start-stream" style="margin-bottom: 10px">Start Face Detection
                </button>
                <canvas id="detect-data" width="600" height="450"></canvas>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        var socket = new WebSocket('ws://localhost:8001/websocket');

        $(document).ready(function () {
            let video = document.getElementById('video');
            let canvas = document.getElementById('canvas');
            let context = canvas.getContext('2d');
            let draw_canvas = document.getElementById('detect-data');
            let draw_context = draw_canvas.getContext('2d');
            let image = new Image();
            if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
                navigator.mediaDevices.getUserMedia({video: true}).then(function (stream) {
                    video.src = window.URL.createObjectURL(stream);
                    video.play();
                });
            }

            function drawCanvas() {
                context.drawImage(video, 0, 0, 600, 450);
                sendMessage(canvas.toDataURL('image/png'));
            }

            document.getElementById("start-stream").addEventListener("click", function () {
                drawCanvas();
            });

            function sendMessage(message) {
                socket.send(message);
            }
            socket.onmessage = function (e) {
                image.onload = function () {
                    draw_context.drawImage(image, 0, 0, 600, 450);
                };
                image.src = e.data;
                drawCanvas();
            };
        })
    </script>
{% endblock %}